### ISSUE TITLE
Create management folder

### ISSUE THREAD

**Issue by jjazz47** [jjazz47/elevator#2]
- Create folder called "management" and "Week1" in the feature branch
- Add an empty MS project file called "elevator" to the "management" folder
- Add a copy of status report template called "week1_status_report"  to the management folder
- Create a file called "logbook" under the "management" folder
- Commit all your changes to the feature branch
- Create a pull request and merge it back to development branch

**Comment by Anand-Queue** [comment]
Commit: https://github.com/jjazz47/elevator/commit/63cc3755ab258e2435ef939541eb22a1bb202355
