### ISSUE TITLE
MS Project: Phase 1 creation

### ISSUE THREAD

**Issue by jjazz47** [jjazz47/elevator#6]
We need to update the MS project file with Work-breakdown structure

-Study phase 1 deliverables
-List all individual tasks base on deliverables
-prioritize tasks based on Must,Should,Could
-Assigned tasks
-Create github issue based on assigned tasks

**Comment by Anand-Queue** [comment]
Commit: https://github.com/jjazz47/elevator/commit/1c4400d054afe7e4c241293cb8c82c8b80606a81

**Comment by Anand-Queue** [comment]
Commit: 5b897bc168c895beb103e9e369a131bf5389e576
